name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Crear carpeta assets si no existe
        run: mkdir -p assets

      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: isi4fire
          image_path: ./assets/thm_propic.png
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit y push
        run: |
          git config user.name "thm-p4p1-bot"
          git config user.email "p4p1@thm.bot"
          git add assets/thm_propic.png
          git commit -m "Updated THM profile badge"
          git push
