name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta todos los días a medianoche UTC
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download TryHackMe Badge from API
        run: |
          mkdir -p assets
          curl -sL "https://tryhackme.com/badge/image/5177834" -o ./assets/tryhackme-badge.png


      - name: Commit and push badge
        run: |
          git add ./assets/tryhackme-badge.png
          git commit -m "Actualizar badge TryHackMe automáticamente" || echo "No hay cambios para commitear"
          git push
