name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta cada día a medianoche
  workflow_dispatch:     # Permite ejecución manual

jobs:
  update-badge:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Fetch TryHackMe Badge
        uses: DhanushNehru/tryhackme-badge-action-workflow@v1.0
        with:
          image_path: './assets/tryhackme-badge.png'
          username: 'isi4fire'
          user_id: '5177834'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

